modLoader="javafml"
loaderVersion="[40,)"
license="GNU Lesser General Public License v3.0"

[[mods]]
modId="mocap"
version="1.0"
displayName="Motion Capture Mod (mocap)"
logoFile="logo.png"
authors="mt1006 (mt1006x)"
credits="Thanks to khitahi for making mod icon"
description="Allows you to record and replay player movements"

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
